index:
   path: /
   controller: App\Controller\QuestionController::getHomepage

newQuestion:
   path: /question/new
   controller: App\Controller\QuestionController::newQuestion

question:
   path: /question/{slug}
   controller: App\Controller\QuestionController::getQuestion

voteComment:
   path: /comments/{id}/vote/{direction<up|down>}
   controller: App\Controller\CommentController::commentVote
   methods: POST

voteQuestion:
   path: /question/{slug}/vote
   methods: POST
   controller: App\Controller\QuestionController::questionVote

# --------------------- Admin -----------------------

createQuestionAdmin:
   path: /admin/question/new
   methods: GET|POST
   controller: App\Controller\QuestionAdminController::create

editQuestionAdmin:
   path: /admin/question/{id}/edit
   methods: GET|POST
   controller: App\Controller\QuestionAdminController::edit

listQuestionAdmin:
   path: admin/question/
   methods: GET
   controller: App\Controller\QuestionAdminController::list

commentAdmin:
   path: /admin/comment
   methods: GET
   controller: App\Controller\CommentAdminController::index

# ----------------- Security ----------------

login:
   path: /login
   methods: GET|POST
   controller: App\Controller\SecurityController::login

logout:
   path: /logout
   methods: GET
   controller: App\Controller\SecurityController::logout

register:
   path: /register
   methods: GET|POST
   controller: App\Controller\SecurityController::register

# --------------------- Account ---------------------------
account:
   path: /account
   methods: GET
   controller: App\Controller\AccountController::index

api_account:
   path: /api/account
   methods: GET
   controller: App\Controller\AccountController::accountApi

