index:
   path: /
   controller: App\Controller\QuestionController::getHomepage

newQuestion:
   path: /question/new
   controller: App\Controller\QuestionController::newQuestion

question:
   path: /question/{slug}
   controller: App\Controller\QuestionController::getQuestion

voteComment:
   path: /comments/{id}/vote/{direction<up|down>}
   controller: App\Controller\CommentController::commentVote
   methods: POST

voteQuestion:
   path: /question/{slug}/vote
   methods: POST
   controller: App\Controller\QuestionController::questionVote

commentAdmin:
   path: /comment/admin
   methods: GET
   controller: App\Controller\CommentAdminController::index
